name: SL Scan

on:
  push:
  schedule:
    - cron: '22 16 * * 5'

jobs:
  Scan-Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Setup Python
      uses: actions/setup-python@main
      with:
        python-version: 3.9
        architecture: x64
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Perform Scan
      uses: ShiftLeftSecurity/scan-action@master
      env:
        WORKSPACE: ""
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SCAN_AUTO_BUILD: true
      with:
        output: reports
        type: credscan, python
    - name: Upload report
      uses: github/codeql-action/upload-sarif@main
      with:
        sarif_file: reports
